name: Deploy plug-in

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to remote server
        uses: easingthemes/ssh-deploy@v4
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ github.ref == 'refs/heads/main' && secrets.REMOTE_USER || secrets.REMOTE_USER_DEV }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ github.ref == 'refs/heads/main' && secrets.REMOTE_PATH || secrets.REMOTE_PATH_DEV }}
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_KEY }}
          ARGS: "-avz --delete"
          EXCLUDE: "/.git/, /.github/"
