---
name: Lint

on:
  push:
    branches: [main]
    paths:
      - '**/*.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpcs.xml'
      - 'phpcs.xml.dist'
      - 'phpstan.neon'
      - 'languages/**'
  pull_request:
    paths:
      - '**/*.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpcs.xml'
      - 'phpcs.xml.dist'
      - 'phpstan.neon'
      - 'languages/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    uses: oszuidwest/.github-templates/.github/workflows/wp-ci.yml@v2
